aoire:
  build: .
  command: ["nodemon", "/app/src/index.js"]
  ports:
    - 3000:3000
  links:
    - db:db
  volumes:
    - ./src:/app/src

nginx:
  build: ./nginx
  links:
    - aoire:aoire
  ports:
    - 80:80

db:
  image: mongo:3.4
  volumes:
    - ./db:/data/db
