aoire:
  build: .
  command: ["bash", "-c", "while true; do nodemon --exitcrash /app/src/index.js; sleep 1; done"]
  ports:
    - 8443:3000
  links:
    - db:db
  volumes:
    - ./src:/app/src

nginx:
  build: ./nginx
  links:
    - aoire:aoire
  ports:
    - 80:80

db:
  image: mongo:3.4
  volumes:
    - ./db:/data/db
